console.log("hello world");
var a = 10;
;
var b = true;
var c = "deepak";
var d;
var myArray = [1, 2, 3];
var myArrayDeclaration;
myArrayDeclaration = [];
myArrayDeclaration = [1, 2];
console.log("My array before push " + myArrayDeclaration);
myArrayDeclaration.push(11);
console.log("My array after push " + myArrayDeclaration);
var popedArray = myArrayDeclaration.pop();
console.log("My array after pop  " + myArrayDeclaration);
//Tuples
var myTuple = [1, "deepak"];
console.log("My tuple is : " + myTuple);
console.log("My number variable " + a);
console.log("my string variable " + b);
console.log("my boolean variable " + c);
console.log("my undefined variable " + d);
console.log("My arra is " + myArray);
